[buoyancy]
speed_divisor = 0.5
shallow_threshold = 3
max_shallow_speed = 4
target_depth = 200
target_depth_2 = 57
hold_duration = 30.0


# target depths are measured at the base of the antenna (blue ring)
# target depth 1 - should be 50cm smaller than the intended depth of the bottom of the BE
# target depth 2 - should be 17cm larger than the intended depth of the top of the BE
